server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog-post
    password: password
    url: jdbc:mysql://localhost:3306/blog_post

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  expiration-time: 1800000
  refresh-expiration-time: 604800000
  secret-key: adfasdfjnonqiero2341234i12312i1201nifqnw0fasdjaniw